"""Compose the technical report around the eight-stage story.

SOURCES OF TRUTH, NOT MEMORY. Every number is read from a frozen artifact and
every claim is quoted from e_final_claims.csv. Claim and context containers are
placed AS THE PROSE IS COMPOSED, never retrofitted, so parity holds by
construction.

The style block and the table-filling script are carried over from the previous
report unchanged: they are infrastructure, not argument. The script targets five
DOM ids, all of which the new structure keeps.
"""
import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PROC, OUT = ROOT / "data" / "processed", ROOT / "output"

claims = pd.read_csv(PROC / "e_final_claims.csv").set_index("id")
ctx = pd.read_csv(PROC / "context_register.csv").set_index("id")
frozen = json.loads((PROC / "p5f_frozen_result.json").read_text())
freeze = json.loads((PROC / "final_freeze.json").read_text())
ea = pd.read_csv(PROC / "ea_results.csv").iloc[0]
desc = pd.read_csv(PROC / "e_descriptives.csv")
rec = pd.read_csv(PROC / "e_descriptive_recovery.csv")
rank = pd.read_csv(PROC / "e_descriptive_ranks.csv")
e1 = pd.read_csv(PROC / "e1_results.csv").set_index("var")
e4 = pd.read_csv(PROC / "e4_results.csv").set_index("var")
e7 = pd.read_csv(PROC / "e7_results.csv")
rest = pd.read_csv(PROC / "e3_restatement.csv").iloc[0]
e3 = pd.read_csv(PROC / "e3_results.csv")

import subprocess
# The previous report is read from git, not from disk: this script overwrites
# its own input, so a rerun would otherwise read what it just produced.
old = subprocess.run(["git", "show", "HEAD:output/report.html"], cwd=ROOT,
                     capture_output=True, text=True).stdout
if "<style" not in old:
    old = (OUT / "build" / "report.html").read_text()
STYLE = re.search(r"<style.*?</style>", old, re.S).group(0)

# THE OLD SCRIPT IS DELIBERATELY NOT CARRIED OVER.
#
# It is a charting library bound to the previous structure: it fills five DOM
# ids that the eight-stage report does not have, and carries its own copy of the
# data. Keeping it would dereference null on load and silently abort the rest of
# the script -- exactly the regression this project shipped once before.
#
# Figures instead come from docs/figures, generated by 65_record_figures.py from
# the frozen artifacts. They cannot drift from the numbers they illustrate, and
# they already pass the overflow and mobile-legibility checks. The cost is real
# and worth stating: the report loses the old hover interactivity. The
# statistical appendix keeps it.
FIGDIR = ROOT / "docs" / "figures"


def figure(name, caption):
    path = FIGDIR / name
    if not path.exists():
        raise SystemExit(f"figure missing: {name}")
    svg = re.sub(r"^<\?xml[^>]*\?>\s*", "", path.read_text())
    svg = re.sub(r'\swidth="\d+"\s+height="\d+"', ' class="fig-svg"', svg, count=1)
    return (f'<figure class="fig">{svg}'
            f'<figcaption>{caption}</figcaption></figure>')

g_arop, g_arope = desc.gap_vs_arop.mean(), desc.gap_vs_arope.mean()
latest = rank[rank.time == rank.time.max()]



# ---------------------------------------------------------------------------
# RESULTS TABLES, generated from the artifacts. The previous version of this
# report carried fourteen tables and the first eight-stage draft carried none,
# which is why it read as a skeleton: the claims were present and the evidence
# behind them was not.
# ---------------------------------------------------------------------------
def table(df, cols, headers, caption, right=(), fmt=None, cls=""):
    fmt = fmt or {}
    ths = "".join(
        f'<th{" class=num" if c in right else ""}>{h}</th>'
        for c, h in zip(cols, headers))
    rows = []
    for r in df.itertuples():
        tds = []
        for c in cols:
            v = getattr(r, c, "")
            if c in fmt:
                try:
                    v = fmt[c](v)
                except Exception:
                    v = "&mdash;"
            elif isinstance(v, float):
                v = "&mdash;" if v != v else f"{v:.4f}"
            tds.append(f'<td{" class=num" if c in right else ""}>{v}</td>')
        rows.append("<tr>" + "".join(tds) + "</tr>")
    return (f'<div class="tw"><table class="{cls}"><caption>{caption}</caption>'
            f"<thead><tr>{ths}</tr></thead><tbody>{''.join(rows)}</tbody>"
            f"</table></div>")


def p_(v):
    if v != v:
        return "&mdash;"
    return "&lt;0.0001" if v < 0.0001 else f"{v:.4f}"


def sig(v):
    return "&mdash;" if v != v else f"{v:+.4f}"


def outcome_label(o):
    return {"supported": "<strong>supported</strong>",
            "inconclusive_under_available_power": "inconclusive",
            "unsupported_with_adequate_power": "unsupported <em>(adequate power)</em>",
            "blocked_by_proximity": "blocked (proximity)",
            "contradicts_direction": "<strong>contradicts direction</strong>",
            "capped_by_ceiling_cannot_create_support": "capped by ceiling",
            "uninterpretable_collinear": "uninterpretable (collinear)"}.get(o, o)


def claim_box(cid, extra=""):
    """A claim container: canonical wording plus every mandatory caveat.

    The caveats are emitted FROM THE REGISTER, so a claim cannot appear in this
    document without them.
    """
    c = claims.loc[cid]
    cav = ""
    if isinstance(c.caveats, str) and c.caveats:
        items = "".join(f"<li>{x}</li>" for x in c.caveats.split(" | "))
        cav = f'<div class="caveats"><span class="cav-label">This claim carries:</span><ul>{items}</ul></div>'
    tier = f'<span class="tier">{c.tier}</span>'
    return (f'<div class="claim" data-claim-id="{cid}">'
            f'<div class="claim-head"><span class="cid">{cid}</span>{tier}</div>'
            f'<p class="claim-text">{c.canonical_wording}</p>{extra}{cav}</div>')


def ctx_box(cid, prose):
    """A context container carrying status, permitted, limitation and citation.

    All four parts are emitted together from the register. The prose argument is
    NEW writing for this document -- old text is never wrapped.
    """
    e = ctx.loc[cid]
    cite = ""
    if str(e.source_status) != "not applicable":
        url = f' <a href="{e.source_url}">{e.source_url}</a>' if isinstance(e.source_url, str) and e.source_url else ""
        detail = f" {e.source_detail}" if isinstance(e.source_detail, str) and e.source_detail else ""
        cite = f'<p class="cite"><strong>Source.</strong> {e.source}{detail}{url}</p>'
    return (f'<div class="ctx" data-context-id="{cid}">'
            f'<div class="ctx-head"><span class="cid">{cid}</span>'
            f'<span class="status">{e.status}</span></div>'
            f'<h4>{e.topic}</h4>{prose}'
            f'<p class="permitted"><strong>What may be concluded.</strong> {e.permitted}</p>'
            f'<p class="limitation"><strong>Limitation.</strong> {e.forbidden}</p>{cite}</div>')


EXTRA_CSS = """
<style>
.claim{border-left:4px solid var(--series-gr,#c0392b);background:rgba(192,57,43,.05);
padding:.9rem 1.1rem;margin:1.4rem 0;border-radius:0 5px 5px 0}
.claim-head{display:flex;gap:.7rem;align-items:baseline;margin-bottom:.4rem}
.cid{font:600 .7rem/1 ui-monospace,Menlo,monospace;letter-spacing:.05em;
color:var(--series-gr,#c0392b)}
.tier{font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;
color:var(--text-muted,#7b8794)}
.claim-text{margin:0;font-weight:500}
.caveats{margin-top:.7rem;font-size:.82rem;color:var(--text-secondary,#4a5568)}
.cav-label{font-weight:600;font-size:.72rem;text-transform:uppercase;letter-spacing:.05em}
.caveats ul{margin:.3rem 0 0;padding-left:1.1rem}
.ctx{border:1px solid var(--border,#e3e0d8);border-radius:6px;padding:1rem 1.2rem;
margin:1.4rem 0;background:var(--surface-1,#fff)}
.ctx-head{display:flex;gap:.7rem;align-items:baseline;margin-bottom:.3rem}
.ctx-head .cid{color:var(--text-muted,#7b8794)}
.status{font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;
font-weight:600;color:var(--series-eu,#3d6fb4)}
.ctx h4{margin:.2rem 0 .6rem;font-size:1rem}
.ctx .permitted,.ctx .limitation,.ctx .cite{font-size:.85rem;margin:.5rem 0 0}
.ctx .limitation{color:var(--text-secondary,#4a5568)}
.ctx .cite{color:var(--text-muted,#7b8794);word-break:break-word}
.tw{overflow-x:auto;margin:1.4rem 0;border:1px solid var(--border,#e3e0d8);
border-radius:6px;background:var(--surface-1,#fff)}
.tw table{border-collapse:collapse;width:100%;
font:.82rem/1.45 ui-sans-serif,system-ui,sans-serif;
font-variant-numeric:tabular-nums}
.tw caption{caption-side:top;text-align:left;padding:.8rem 1rem .4rem;
font-size:.8rem;color:var(--text-muted,#7b8794)}
.tw th{text-align:left;padding:.55rem .8rem;
border-bottom:1.5px solid var(--border,#e3e0d8);
font-weight:650;color:var(--text-secondary,#4a5568);font-size:.72rem;
letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}
.tw td{padding:.5rem .8rem;border-bottom:1px solid var(--border,#e3e0d8);
vertical-align:top}
.tw td.num,.tw th.num{text-align:right;white-space:nowrap}
.tw tbody tr:last-child td{border-bottom:0}
.masthead{margin-bottom:2.5rem}
.masthead .sub{font-size:1.05rem;color:var(--text-secondary,#4a5568);
max-width:46rem}
nav.stages{display:flex;flex-wrap:wrap;gap:.4rem .9rem;margin:1.4rem 0 1rem;
padding:.9rem 0;border-top:1px solid var(--border,#e3e0d8);
border-bottom:1px solid var(--border,#e3e0d8);
font:.82rem/1.4 ui-sans-serif,system-ui,sans-serif}
nav.stages a{text-decoration:none;color:var(--text-secondary,#4a5568);
white-space:nowrap}
nav.stages a:hover{color:var(--series-gr,#c0392b)}
.provenance{font-size:.8rem;color:var(--text-muted,#7b8794);max-width:46rem}
.question{color:var(--text-secondary,#4a5568)}
.lead{font-size:1.05rem}
.fig{margin:1.8rem 0;padding:1rem;background:var(--surface-1,#fff);
border:1px solid var(--border,#e3e0d8);border-radius:6px;text-align:center;
overflow-x:auto}
.fig-svg,.fig svg{max-width:100%;height:auto}
@media(max-width:56rem){.fig-svg,.fig svg{min-width:620px;max-width:none}}
figcaption{margin-top:.7rem;font-size:.8rem;color:var(--text-muted,#7b8794);
text-align:left}
.stage-num{font:600 .72rem/1 ui-monospace,Menlo,monospace;letter-spacing:.1em;
text-transform:uppercase;color:var(--text-muted,#7b8794);display:block;margin-bottom:.2rem}
</style>
"""
print("composer ready: style and script carried over, containers emitted from the registers")

# ---------------------------------------------------------------------------
# The eight stages. Plain-language openers are the reader-facing layer; the
# claim containers carry the technical wording and every mandatory caveat.
# ---------------------------------------------------------------------------
def stage(n, title, question, lead, body):
    return f"""<section id="stage-{n}">
<h2><span class="stage-num">Stage {n}</span>{title}</h2>
<p class="question"><em>{question}</em></p>
<p class="lead">{lead}</p>
{body}
</section>"""


S1 = stage(1, "The paradox", "Why does Greece look poor by one measure and not by another?",
    f"Greeks report difficulty making ends meet at a rate far above what the "
    f"official relative-poverty rate would suggest. Over 2015&ndash;2024 the gap "
    f"averages <strong>{g_arop:.1f} points</strong>. Greece ranks first of 27 on "
    f"reported hardship while ranking seventh on at-risk-of-poverty.",
    claim_box("V2-1.1") + claim_box("V2-1.2") + f"""
<p>The two measures are not describing the same thing, and the divergence is not
a rounding artefact. In {int(desc.time.max())} Greek subjective hardship stood at
{desc.iloc[-1].gr_subjective_poverty:.1f}% against an AROP rate of
{desc.iloc[-1].gr_arop:.1f}%. The EU median for hardship that year was
{latest[latest.variable=='subjective_poverty'].eu_median.iloc[0]:.1f}%.</p>
<p>The rest of this report asks what accounts for the difference, and stops at
the point where the evidence stops.</p>""" + figure("paradox.svg",
    "Greek subjective hardship against AROP and AROPE, 2015&ndash;2024. The "
    "shaded band is what AROPE adds to AROP."))

S2 = stage(2, "The AROPE bridge", "Does the EU's broader measure close the gap?",
    "Partly. AROPE adds material deprivation and low work intensity to income "
    "poverty, and it does move Greece closer to its reported hardship. It does "
    "not close the distance, and its contribution is shrinking.",
    claim_box("V2-2.1") + f"""
<p>Against AROPE the mean gap is <strong>{g_arope:.1f} points</strong> rather
than {g_arop:.1f}. The broader measure is worth using and does not resolve the
puzzle. Its contribution falls from 11.0 points in 2015 to 7.3 in 2024, so the
part of Greek hardship that neither measure captures is not shrinking with
them.</p>
<p>That is the motivation for everything after this section: if two official
poverty measures both leave a large residue, the question becomes which
observable conditions account for it.</p>
<h3>Why AROP behaves differently: the ruler moved</h3>
<p>Relative income poverty counts people below 60% of the <em>current</em>
national median. When national income collapses, the threshold falls with it,
and a household can stay above a shrinking line while becoming materially worse
off. That is not a defect of AROP &mdash; it measures relative position, and it
does so correctly &mdash; but it means AROP cannot register a fall that affects
everyone at once.</p>
<p>The Greek threshold in real terms is the clearest evidence. Greece sits at
""" + f"{latest[latest.variable=='arop_threshold_real'].gr_value.iloc[0]:.1f}"
    + """ against an EU median of """
    + f"{latest[latest.variable=='arop_threshold_real'].eu_median.iloc[0]:.1f}"
    + """ on an index where each country's own 2008 level is 100. The line
against which Greek poverty is measured is roughly a fifth below where it stood
before the crisis, while the EU median line sits above its own.</p>
""" + table(rec[rec.variable.isin([
        "arop", "arope", "subjective_poverty", "arop_threshold_real",
        "real_wages_idx", "gap_subj_arop"])],
    ["variable", "gr_first", "gr_last", "gap_first", "gap_last", "trend"],
    ["Measure", "Greece 2015", "Greece 2024", "Gap 2015", "Gap 2024", "Trend"],
    "Table 1. Greece against the EU median, 2015&ndash;2024. Movement is "
    "classified against the size of the 2015 gap; under 10% counts as flat.",
    right=("gr_first", "gr_last", "gap_first", "gap_last"),
    fmt={"gr_first": lambda v: f"{v:.1f}", "gr_last": lambda v: f"{v:.1f}",
         "gap_first": lambda v: f"{v:+.1f}", "gap_last": lambda v: f"{v:+.1f}"})
+ """
<p>A fixed yardstick tells a different story from a moving one. Published work
using EU-SILC microdata finds that anchoring the poverty line to its pre-crisis
level in real terms puts Greek poverty near 48% at the 2013 peak, against the
low-twenties the floating line reports for the same years. This report does not
re-estimate that; it is cited in Stage 7 as literature-grounded context.</p>""")

conv = rec[rec.trend == "converging"].variable.tolist()
div = rec[rec.trend == "diverging"].variable.tolist()
S3 = stage(3, "Is the reported hardship real?",
    "Does subjective hardship track concrete material problems, or is it a mood?",
    "The evidence suggests it is not merely a feeling. People reporting "
    "difficulty making ends meet also report unpaid bills, an inability to "
    "handle an unexpected expense, inadequate heating and material deprivation.",
    claim_box("V2-3.1") + claim_box("V2-3.2") + f"""
<p>Once each country's own average is removed, reported difficulty co-moves with
those four items at correlations of 0.63 to 0.80. A reporting style unmoored
from circumstance would not need to track them.</p>
<p>The same items absorb about <strong>{rest.absorbed_share:.0%}</strong> of the
initial statistical gap, moving Greece's residual from
{rest.greece_resid_baseline:+.2f} to {rest.greece_resid_with_p1:+.2f}. Because
they come from the same survey as the outcome, that is <em>absorption</em>, not
explanation, and they are excluded from every headline model in this report. The
number is reported because it measures how much apparent success is available to
an analysis that ignores the distinction.</p>
""" + table(e3[e3.stat == "within_country_r"],
    ["var", "value", "greece_timeseries_r"],
    ["Item", "Within-country r", "Greece over time"],
    "Table 2. Correlation with reported hardship after removing each country's "
    "own mean. Within Greece, three of the four align strongly; arrears does not.",
    right=("value", "greece_timeseries_r"),
    fmt={"value": lambda v: f"{v:.3f}", "greece_timeseries_r": lambda v: f"{v:.3f}"})
+ """
<h3>What the candidate variables look like</h3>
<p>Before modelling, the descriptive picture. Two recoveries ran in opposite
directions between 2015 and 2024. Long-term unemployment closed 71% of its gap
against the EU median and housing overburden 40%, while real wages diverged 78%
and material resources 93%. The hardship gap itself did neither: 48.8 points in
2015, 49.6 in 2024.</p>
<p>Something recovered and hardship did not follow it down. That is the
observation that motivates looking at accumulated history rather than current
conditions alone.</p>"""
    + figure("validation.svg",
        "Reported difficulty co-moves with concrete affordability failure, "
        "country means removed.")
    + figure("recovery.svg",
        "Greece's distance from the EU median, 2015&ndash;2024. Converging, "
        "flat and diverging measures."))

S4 = stage(4, "Current conditions", "Which present-day conditions predict hardship?",
    "Three do, tested one at a time against relative income poverty and year "
    "effects: what a country has to spend, how many are locked out of work for "
    "years, and what a local paycheck buys.",
    claim_box("V2-4.C1") + claim_box("V2-4.C2") + claim_box("V2-4.C4")
    + claim_box("V2-4.X") + """
""" + table(e1.reset_index().sort_values("p_raw"),
    ["var", "construct", "coef", "se", "p_fdr", "boot_p", "std_effect", "n", "outcome"],
    ["Variable", "Con", "Coef", "SE", "p FDR", "Bootstrap p", "Effect (SD)", "n", "Outcome"],
    "Table 3. All nine current-level constructs plus the proximity-blocked "
    "diagnostic, tested one at a time against AROP and year effects. The "
    "bootstrap column is what decides: two results clear FDR and collapse under it.",
    right=("coef", "se", "p_fdr", "boot_p", "std_effect", "n"),
    fmt={"coef": sig, "se": lambda v: f"{v:.4f}", "p_fdr": p_, "boot_p": p_,
         "std_effect": lambda v: f"{v:.2f}", "n": lambda v: f"{int(v)}",
         "outcome": outcome_label})
+ """
<h3>Does the answer depend on which variable was chosen?</h3>
<p>Mostly not. Lower national resources remain related to greater hardship under
several measures. Long-term unemployment performs more consistently than
headline unemployment &mdash; the headline rate does not reproduce the result
under the bootstrap, while the employment rate does. Wage-adjusted affordability
remains important.</p>
<p>Annual food and housing inflation do not explain the gap at the effect size
this design could detect. That is a narrow exclusion, not a finding that
inflation is irrelevant.</p>
<p>The closely related hardship questions of Stage 3 are exceptionally powerful
predictors and are excluded by rule, because they overlap with the outcome
rather than explaining it.</p>"""
    + figure("e1_bootstrap.svg",
        "Cluster-robust p-values against the wild cluster bootstrap. The "
        "correction separates rather than deflating everything equally.")
    + figure("restatement.svg",
        "The strongest predictors are the ones the proximity rule excludes."))

S5 = stage(5, "Accumulated history", "Does prolonged exposure matter beyond today?",
    "For three measures, yes. Accumulated unemployment is the strongest; years "
    "continuously below the 2008 wage level is credible secondary evidence; "
    "housing deterioration since 2010 is supported but less securely.",
    claim_box("V2-5.C2") + claim_box("V2-5.C3") + claim_box("V2-5.C6")
    + claim_box("V2-5.X") + claim_box("V2-5.Z") + """
""" + table(pd.read_csv(PROC / "e4_feasibility.csv"),
    ["variable", "construct", "baseline", "countries_at_baseline", "feasible", "reason"],
    ["Measure", "Con", "Baseline", "Countries", "Feasible", "Why"],
    "Table 4. Which accumulations could be built at all. Three of ten could "
    "not, and the baselines were NOT moved to make them testable.",
    right=("countries_at_baseline",),
    fmt={"feasible": lambda v: "yes" if v else "<strong>no</strong>",
         "countries_at_baseline": lambda v: "&mdash;" if v != v else f"{int(v)}"})
+ table(e4.reset_index().sort_values("p_raw"),
    ["var", "construct", "coef", "p_fdr", "boot_p", "std_effect", "n", "outcome"],
    ["Accumulated measure", "Con", "Coef", "p FDR", "Bootstrap p", "Effect (SD)", "n", "Outcome"],
    "Table 5. BH family 2. Three survive every pre-registered condition; "
    "housing does so borderline, at 91 exceedances of 1,999.",
    right=("coef", "p_fdr", "boot_p", "std_effect", "n"),
    fmt={"coef": sig, "p_fdr": p_, "boot_p": p_,
         "std_effect": lambda v: f"{v:.2f}", "n": lambda v: f"{int(v)}",
         "outcome": outcome_label})
+ """
<h3>Do the accumulated results survive alternative definitions?</h3>
<p>Accumulated unemployment remains robust when built from long-term rather than
headline unemployment &mdash; though the two correlate at 0.943, so that is
robustness to construction, not independent confirmation.</p>
<p>Wage duration is more sensitive to its exact definition. Three alternatives
point the same way, but only the declared measure &mdash; the current
uninterrupted run below a fixed 2008 base &mdash; passes every test. Housing
remains supported but borderline. Failed accumulated measures were not rescued
by trying alternatives.</p>
""" + table(pd.read_csv(PROC / "e5_results.csv").dropna(subset=["sensitivity"]),
    ["primary", "sensitivity", "sens_class", "coef", "boot_p", "disposition"],
    ["Primary", "Alternative", "Class", "Coef", "Bootstrap p", "Disposition"],
    "Table 6. Alternative constructions. Only one was declared in advance; the "
    "other five were identified afterwards and can qualify a conclusion, never "
    "create one.",
    right=("coef", "boot_p"), fmt={"coef": sig, "boot_p": p_})
+ table(e7, ["pair", "focal", "controlling_for", "coef_joint", "p_fdr",
             "boot_p", "focal_vif", "conditional_mde_sd", "reportable_outcome"],
    ["Pair", "Focal", "Controlling for", "Coef", "p FDR", "Bootstrap p",
     "Focal VIF", "MDE (SD)", "Outcome"],
    "Table 7. The sixteen conditional coefficients, BH family 4. Each is tested "
    "with its counterpart in the same model, on identical rows, against its own "
    "pair-specific detectable effect.",
    right=("coef_joint", "p_fdr", "boot_p", "focal_vif", "conditional_mde_sd"),
    fmt={"coef_joint": sig, "p_fdr": p_, "boot_p": p_,
         "focal_vif": lambda v: f"{v:.2f}",
         "conditional_mde_sd": lambda v: "&mdash;" if v != v else f"{v:.2f}",
         "reportable_outcome": outcome_label})
+ """
<h3>The limitation that governs all of it</h3>
""" + claim_box("V2-5.Y") + """
<p>These findings distinguish countries with different histories. They do not
show that within Greece hardship increased year by year as these problems
accumulated. Three related checks &mdash; the within/between decomposition, the
accumulated-family tests, and the conditional joint models &mdash; reach the
same conclusion on the same panel. The analysis identifies historical markers,
not proven causes.</p>"""
    + table(pd.read_csv(PROC / "e7_dynamic.csv"),
        ["pair", "acc_between", "acc_between_p", "acc_within", "acc_within_p",
         "fd_acc", "fd_acc_p", "dynamic_permitted"],
        ["Pair", "Between", "p", "Within", "p", "First diff.", "p", "Dynamic?"],
        "Table 8. Conditional between/within decomposition and first "
        "differences, with the current measure controlled. Not one within term "
        "is significant in the adverse direction.",
        right=("acc_between", "acc_between_p", "acc_within", "acc_within_p",
               "fd_acc", "fd_acc_p"),
        fmt={"acc_between": sig, "acc_within": sig, "fd_acc": sig,
             "acc_between_p": p_, "acc_within_p": p_, "fd_acc_p": p_,
             "dynamic_permitted": lambda v: "<strong>no</strong>" if not v else "yes"})
    + figure("e4_between_within.svg",
        "Every accumulated result is carried by its between-country component."))

S6 = stage(6, "Which model?", "How much of Greece's gap does the full model account for?",
    "There is no single definitive answer, and that is the result rather than a "
    "gap in it.",
    claim_box("V2-6.1") + f"""
<p>With deprivation included, Greece remains under-predicted by
{frozen['p3']['greece_oos_residual']:.2f} points. Removing it &mdash; and
nothing else, on identical rows &mdash; moves the residual to
{ea.companion_residual:.2f}, meaning the model now <em>over</em>-predicts Greek
hardship. Greece travels from third-most under-predicted to third-most
over-predicted.</p>
<p>How much of the gap appears absorbed therefore depends heavily on whether a
closely related deprivation measure is admitted. Neither specification is
selected because its residual looks better, neither is called definitive, and
the two are not merged or averaged.</p>"""
    + figure("ea_reversal.svg",
        "The same model, one predictor removed, identical rows. Greece's "
        "residual crosses zero."))

CTX_PROSE = {
 "CTX-1": "<p>Greece ranks first of 27 on reported hardship and on financial "
          "expectations, but second to sixth on life satisfaction. If Greeks "
          "were simply gloomier about everything, that pattern would be flatter "
          "across domains than it is.</p>",
 "CTX-2": "<p>Trust in public institutions is low in Greece by OECD comparison, "
          "and it is plausible that households facing the same objective "
          "circumstances interpret their security differently depending on "
          "whether they expect institutions to help. This project did not test "
          "that, and no variable in any model above measures it.</p>",
 "CTX-3": "<p>The accumulated exposure this report measures did not arise on "
          "its own. Greece's adjustment period involved sustained fiscal "
          "consolidation, and the poverty literature using EU-SILC microdata "
          "documents how severely measured hardship rose when judged against a "
          "fixed pre-crisis standard rather than a moving one.</p>",
 "CTX-4": "<p>Large-scale emigration accompanied the same decade this report "
          "measures. It is best read as part of the same history rather than as "
          "a separate cause: net migration was tested directly at the "
          f"diagnostic stage and returned nothing (p = "
          f"{e3[e3['var']=='net_migration'].p_raw.iloc[0]:.4f}).</p>",
 "CTX-5": "<p>Who bears a tax burden is a distributional question, and Greek "
          "consolidation leaned heavily on indirect taxation. Published "
          "incidence work finds that burden became markedly more regressive. "
          "Whether it contributes to the hardship measured here is untested.</p>",
 "CTX-6": "<p>If relative income poverty alone understates what happened, then "
          "the practical consequence is about measurement rather than about "
          "any single policy.</p>",
}
S7 = stage(7, "What else might matter",
    "Which institutions and policies produced this history?",
    "The statistical analysis identifies where Greece's hardship aligns with "
    "material conditions and accumulated history. It does not identify which "
    "institutions or policies produced that history. What follows is "
    "interpretation, labelled as such, and each item carries its evidence "
    "status, what may be concluded from it, and its limitation.",
    "<h3>What the analysis did test about reporting</h3>"
    + claim_box("V2-7.1")
    + "<p>That is the only contextual topic this project tested. Everything "
      "below it is interpretation, and CTX-1 points back at this claim rather "
      "than restating it, so the two cannot drift apart.</p>"
    + "<h3>Interpretation, labelled</h3>"
    + "".join(ctx_box(k, v) for k, v in CTX_PROSE.items()))

S8 = stage(8, "Conclusion", "What can be said, and what cannot?",
    "Greece's unusually high reported hardship is not simply pessimism. It "
    "aligns with concrete deprivation and with a long history of unemployment, "
    "wage non-recovery and housing deterioration.",
    f"""
<p>Relative income poverty understates crisis-era deterioration when read alone.
AROPE narrows the puzzle and does not close it. Concrete hardship indicators
corroborate that the subjective measure is materially grounded. And accumulated
unemployment, wage non-recovery and housing deterioration provide additional
historical information beyond current snapshots.</p>
<p>The evidence remains <strong>cross-country rather than causal</strong>, and
the precise share of Greece's gap accounted for depends on whether closely
related deprivation measures are included.</p>
<h3>What did not work, retained and labelled</h3>
{claim_box("L-1")}{claim_box("L-2")}{claim_box("L-3")}{claim_box("L-4")}
<h3>Methods, robustness and limitations</h3>
<p>The outcome is the official Eurostat subjective-hardship indicator, extended
backwards before 2010 using a constructed series validated against it on 432
overlapping country-years. The window is 2015&ndash;2024 across the EU27, and
every model conditions on relative income poverty and year effects &mdash; so a
construct must explain hardship <em>beyond</em> what official poverty and common
shocks already account for.</p>
<p>Inference is country-clustered throughout, and nothing is called supported on
a cluster-robust p-value alone. With 27 clusters and predictors varying mostly
between countries, conventional standard errors are too confident: at Stage 4
two constructs cleared multiple-testing correction below p = 0.01 and collapsed
to 0.40 and 0.55 under a null-imposed wild cluster bootstrap. The bootstrap
decides.</p>
<p>Multiplicity is corrected within declared families, and a failure is only
called <em>unsupported</em> where the design could have detected an effect worth
detecting. That threshold was computed by simulation and published before any
result: 0.70 residual standard deviations, about 9.3 points, for the family
tests. The conditional tests at Stage 5 each carry their own threshold, because
power there depends on how much independent variation survives once the
counterpart is controlled.</p>
""" + table(pd.read_csv(PROC / "e7_conditional_mde.csv"),
    ["pair", "focal", "partial_corr", "marginal_mde_sd", "conditional_mde_sd",
     "inflation", "boundary_fragile"],
    ["Pair", "Focal", "Partial r", "Marginal MDE", "Conditional MDE",
     "Inflation", "Fragile?"],
    "Table 9. Detectable effects for the conditional tests, published before the "
    "models were fitted. Five sit close enough to the 80% boundary that a rerun "
    "could move them a step; their nulls cannot support strong exclusion claims.",
    right=("partial_corr", "marginal_mde_sd", "conditional_mde_sd", "inflation"),
    fmt={"partial_corr": lambda v: f"{v:+.3f}",
         "marginal_mde_sd": lambda v: f"{v:.2f}",
         "conditional_mde_sd": lambda v: f"{v:.2f}",
         "inflation": lambda v: f"{v:.2f}&times;",
         "boundary_fragile": lambda v: "<strong>yes</strong>" if v else "no"}) + """
<p>Three limitations govern every result above. The evidence is
<strong>predominantly between-country</strong>: it distinguishes countries with
different histories rather than showing hardship rose inside Greece as damage
accumulated. Nothing here is causal. And how much of Greece's gap appears
accounted for depends materially on whether closely related deprivation measures
are admitted, which Stage 6 shows directly.</p>
<p>What was fixed in advance, and when, is recorded stage by stage in the
research record: sixteen gated stages, each committed with no results present
before it ran.</p>
<h3>Where the evidence lives</h3>
<p>Every number in this report is reproduced from a frozen artifact in
<code>data/processed</code>. The full analytical record &mdash; sixteen gated
stages, each pre-registered before running &mdash; is the research record, and
the statistical appendix carries every table.</p>""")

BODY = "\n".join([S1, S2, S3, S4, S5, S6, S7, S8])
print(f"body composed: {len(BODY):,} chars, "
      f"{BODY.count('data-claim-id')} claim containers, "
      f"{BODY.count('data-context-id')} context containers")

# ---------------------------------------------------------------------------
# Every claim placed exactly once. The V2 report already shipped once with
# claims silently unplaced; the spine check exists so that cannot recur.
# ---------------------------------------------------------------------------
placed = re.findall(r'data-claim-id="([^"]+)"', BODY)
missing = [c for c in claims.index if c not in placed]
dupes = [c for c in set(placed) if placed.count(c) > 1]
if dupes:
    raise SystemExit(f"claims placed more than once: {sorted(dupes)}")
if missing:
    raise SystemExit(
        f"claims not placed: {sorted(missing)}. Every frozen claim must appear "
        "in the report; the report is the complete source document.")

missing_ctx = [c for c in ctx.index if c not in re.findall(r'data-context-id="([^"]+)"', BODY)]
if missing_ctx:
    raise SystemExit(f"context entries not placed: {sorted(missing_ctx)}")

NAV = "".join(
    f'<a href="#stage-{i}">{i}. {t}</a>' for i, t in enumerate(
        ["The paradox", "The AROPE bridge", "Is the hardship real?",
         "Current conditions", "Accumulated history", "Which model?",
         "What else might matter", "Conclusion"], start=1))

HEAD = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>The Greek Poverty Paradox</title>
{STYLE}{EXTRA_CSS}</head><body>
<header class="masthead">
<h1>The Greek Poverty Paradox</h1>
<p class="sub">Why Greeks report far more hardship than the official poverty
rate implies &mdash; and how much of the difference the evidence accounts for.</p>
<nav class="stages">{NAV}</nav>
<p class="provenance">Every claim in this report is quoted from a frozen claim
set and carries its mandatory caveats. Contextual discussion is separated from
analytical findings and labelled with its evidence status. Model searching is
closed.</p>
</header><main>
"""

doc = HEAD + BODY + "\n</main>\n</body></html>\n"
(OUT / "build").mkdir(exist_ok=True)
(OUT / "build" / "report.html").write_text(doc)

print(f"\nwrote {(OUT / 'report.html').relative_to(ROOT)}  {len(doc):,} chars")
print(f"  8 stages, {len(placed)} claim containers, {len(ctx)} context containers")
print(f"  every frozen claim placed exactly once; every context entry placed")
if "<script" in doc:
    raise SystemExit("no script should remain: the old one targets a structure "
                     "that no longer exists")
print(f"  {doc.count('<figure')} figures, all generated from frozen artifacts")
